app/cart/__init__.py
from . import views
from flask import Blueprint


cart_bp = Blueprint('cart', __name__)

app/cart/views.py
# from flask import render_template, redirect, url_for, session, request, flash
# from flask_login import login_required
# from bson import ObjectId
# from . import cart_bp
# from . import mongo

# @cart_bp.route('/cart')
# @login_required
# def cart():
#     session['cart'] = cart_items
#     # Assuming the cart is stored in the session
#     cart_items = session.get('cart', [])
    
#     # Calculate the total amount
#     total_amount = sum(item['price'] * item['quantity'] for item in cart_items)

#     return render_template('cart.html', cart_items=cart_items, total_amount=total_amount)

# # Route to add items to the cart
# @cart_bp.route('/add_to_cart/<product_id>', methods=['POST'])
# @login_required
# def add_to_cart(product_id):
#     product = mongo.db.products.find_one({'_id': ObjectId(product_id)})
#     if not product:
#         flash('Product not found', 'danger')
#         return redirect(url_for('main.get_images', folder_name='products'))

#     # Get the quantity from the form
#     quantity = int(request.form.get('quantity', 1))

#     # Add the product to the cart (stored in the session)
#     cart = session.get('cart', [])
    
#     # Check if the product is already in the cart
#     for item in cart:
#         if item['_id'] == product['_id']:
#             item['quantity'] += quantity
#             break
#     else:
#         # Add new product to cart
#         cart.append({
#             '_id': str(product['_id']),
#             'name': product['name'],
#             'price': product['price'],
#             'quantity': quantity
#         })

#     # Save the cart back to the session
#     session['cart'] = cart

#     flash(f'{product["name"]} added to cart!', 'success')
#     return redirect(url_for('main.cart'))

# # Route to remove items from the cart
# @cart_bp.route('/remove_from_cart/<product_id>', methods=['POST'])
# @login_required
# def remove_from_cart(product_id):
#     cart = session.get('cart', [])
    
#     # Filter out the product from the cart
#     cart = [item for item in cart if item['_id'] != product_id]

#     # Save the updated cart back to the session
#     session['cart'] = cart

#     flash('Item removed from cart', 'success')
#     return redirect(url_for('main.cart'))

# # Checkout route
# @cart_bp.route('/checkout', methods=['POST'])
# @login_required
# def checkout():
#     # Process the checkout
#     cart = session.get('cart', [])
    
#     if not cart:
#         flash('Your cart is empty', 'danger')
#         return redirect(url_for('main.cart'))
    
#     # Here you can add the logic for payment processing, saving the order, etc.
#     session.pop('cart', None)  # Clear the cart after checkout
#     flash('Checkout successful! Thank you for your purchase.', 'success')
    
#     return redirect(url_for('main.get_images', folder_name='products'))

app/routes.py
from flask import Blueprint, request, session, jsonify
from flask import render_template, redirect, url_for, request, flash, current_app, send_file
from flask_login import login_user, login_required, logout_user
import requests.exceptions
from .forms import Admin, RegistrationForm, LoginForm
from gridfs import GridFS
import os
from app import mongo, bcrypt, csrf
from app.models import User
from bson.objectid import ObjectId
import json
from dotenv import load_dotenv
import requests
import json
import base64
from datetime import datetime
from  functools import wraps



load_dotenv()

main_bp = Blueprint('main', __name__)

fs = GridFS(mongo.db)


@main_bp.before_request
def ensure_cart_exists():
    if 'cart' not in session:
        session['cart'] = [] 

def admin_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        # Checking if the user is logged in and is an admin
        if 'user_role' not in session or session['user_role'] != 'admin':
            flash('You do not have permission to access this page.', 'danger')
            return redirect(url_for('main.index'))
        return f(*args, **kwargs)
    return decorated_function

@main_bp.route('/')
def index():
    return render_template('homepage.html')


@main_bp.route('/register', methods=['GET', 'POST'])
def register():
    from .models import User

    form = RegistrationForm()
    if form.validate_on_submit():
        if form.password.data == form.confirm_password.data:
            username = form.username.data
            email = form.email.data
            password = form.password.data
            hashed_password = bcrypt.generate_password_hash(password).decode('utf8')

            # Inserting user into the database
            mongo.db.users.insert_one({'Username': username, 'Email': email, 'Password': hashed_password})
            
            # Creating a user object and log them in
            user_dict = mongo.db.users.find_one({'Email': email})
            user = User(user_dict)
            login_user(user)

            flash(f'Account created for {username}!', 'success')
            return redirect(url_for('main.get_images', folder_name='products'))
        else:
            flash('Passwords do not match!', 'danger')
    return render_template('register.html', form=form)


@main_bp.route('/home', methods=['GET'])
def home():
    images = ['url_for(main.get_images)']
    folder_name = 'products'
    page = 1
    total_pages = 7

    return render_template('product_list.html', images=images, folder_name=folder_name, page=page, total_pages=total_pages)

@main_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        user_dict = mongo.db.users.find_one({'Email': email})

        if user_dict:
            # Checking password hash
            if bcrypt.check_password_hash(user_dict['Password'], password):
                user = User(user_dict)
                login_user(user)
                return redirect(url_for('main.get_images', folder_name='products'))
            else:
                return 'Incorrect password. Please try again.', 'danger'
        else:
            return redirect(url_for('main.register'))
    else:
        return render_template('login.html', form=form)

@main_bp.route('/admin/dashboard')
@login_required
def admin():
    return render_template('admin_dashboard.html')


@main_bp.route('/admin_login', methods=['GET', 'POST'])
def admin_login():
    form = Admin()

    # Admin credentials stored in environment variables
    admin_email = os.getenv('ADMIN_EMAIL')
    admin_pass = os.getenv('ADMIN_PASSWORD')

    if form.validate_on_submit() and request.method == 'POST':
        email = form.email.data
        password = form.password.data

        # Checking if the provided email matches the admin email
        if email == admin_email:
            # Checking if the provided password matches the hashed admin password
            if bcrypt.check_password_hash(admin_pass, password):
                # If credentials are correct, set session
                session['admin_logged_in'] = True
                session['admin_email'] = email

                # Redirect to the admin dashboard
                return redirect(url_for('main.admin'))
            else:
                flash("Invalid password. Please try again.", "danger")
        else:
            flash("Invalid email. Please try again.", "danger")
    
    return render_template('admin_login.html', form=form)


@main_bp.route('/upload-images')
@admin_required
def upload_images():
    images_path = os.path.join(current_app.root_path, 'static/images')

    # Fetching all products from MongoDB
    products = mongo.db.products.find()

    # Creating a dictionary to quickly access product metadata by filename
    product_metadata = {}
    for product in products:
        product_metadata[product['filename']] = {
            'name': product.get('name', 'No name available'),
            'description': product.get('description', 'No description available'),
            'price': product.get('price', 'N/A'),
            'inStock': product.get('inStock', False)
        }

    # Iterating over all directories and files in the images_path
    for root, files in os.walk(images_path):
        for file in files:
            file_path = os.path.join(root, file)
            file_name = os.path.relpath(file_path, images_path)
            folder_name = os.path.basename(root)  # Get the folder name

            # Checking if file already exists in GridFS
            existing_file = fs.find_one({'filename': file_name})
            if existing_file:
                print(f"File '{file_name}' already exists in MongoDB.")
                continue

            # Fetching the metadata for the current file
            metadata = product_metadata.get(file_name, {
                "name": "Sample Product",
                "description": "Sample product description.",
                "price": 10.99,
                "inStock": True
            })

            # Opening and uploading the file to GridFS with folder and product metadata
            with open(file_path, 'rb') as f:
                fs.put(f, filename=file_name, metadata={
                    'folder': folder_name,
                    'description': json.dumps(metadata)  # Store metadata as a JSON string
                })

    flash('All images have been uploaded successfully.')
    return redirect(url_for('main.index'))

@main_bp.route('/images/<folder_name>', methods=['GET'])
@login_required
def get_images(folder_name):
    page = int(request.args.get('page', 1))
    per_page = int(request.args.get('per_page', 20))
    search_query = request.args.get('search', '')

    skip = (page - 1) * per_page
    limit = per_page

    # Building the query to search images
    query = {'metadata.folder': folder_name}
    if search_query:
        query['filename'] = {'$regex': search_query, '$options': 'i'}  # Case-insensitive search

    # Finding images based on the query
    total_files = mongo.db.fs.files.count_documents(query)
    files = fs.find(query).skip(skip).limit(limit)

    image_list = []
    for file in files:
        # Accessing the description field if it exists
        description_data = getattr(file, 'description', None)
        if description_data:
            try:
                description = json.loads(description_data)
            except json.JSONDecodeError:
                description = {"description": "No valid description available."}
        else:
            description = {"description": "No description available."}

        # Appending the necessary data to the image list
        image_list.append({
            '_id': str(file._id),
            'filename': file.filename,
            'url': url_for('main.static_image', filename=file.filename),
            'description': description.get('description', 'No description available'),
            'name': description.get('name', 'No name available'),
            'price': description.get('price', 'N/A'),
            'inStock': description.get('inStock', False)
        })

    # Calculating total pages
    total_pages = (total_files + per_page - 1) // per_page

    return render_template('product_list.html', images=image_list, folder_name=folder_name, page=page, total_pages=total_pages)


@main_bp.route('/static/images/<filename>')
def static_image(filename):
    
    file = fs.find_one({'filename': filename})
    if file:
        return send_file(file, mimetype='image/jpeg')
    print(f'File not found: {filename}')
    return redirect(url_for('main.home'))

@main_bp.route('/products/<product_id>', methods=['GET'])
@login_required
def product_detail(product_id):
    try:
        # Fetching the product using its _id from GridFS
        file = fs.get(ObjectId(product_id))
    except Exception as e:
        print(f"Error fetching file: {e}")
        return "Product not found", 404

    if file:
        # Extracting description data and clean it
        description_data = file.description
        print(f"Raw description data: {description_data}")

        # Cleaning the description_data to remove unwanted characters
        description_data_cleaned = description_data.replace('\n', '').strip()
        print(f"Cleaned description data: {description_data_cleaned}")

        try:
            description = json.loads(description_data_cleaned)
        except json.JSONDecodeError as e:
            print(f"Error parsing JSON: {e}")
            description = {
                "name": "No name available",
                "description": "No description available",
                "price": "N/A",
                "inStock": False
            }

        # Preparing the product data to pass to the product detail
        image = {
            '_id': str(file._id),
            'filename': file.filename,

app/templates/admin_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/admin_login.css') }}">
</head>
<body>
    <form action="{{ url_for('main.admin_login') }}" method="POST">
        {{ form.hidden_tag() }}

        <div class="form-group">
            {{ form.email.label }}<br>
            {{ form.email(size=32, placeholder="Enter your email") }}<br>
            {% for error in form.email.errors %}
                <span class="error">[{{ error }}]</span>
            {% endfor %}
        </div>

        <div class="form-group">
            {{ form.password.label }}<br>
            {{ form.password(size=32, placeholder="Enter your password") }}<br>
            {% for error in form.password.errors %}
                <span class="error">[{{ error }}]</span>
            {% endfor %}
        </div>

        <div class="form-group">
            {{ form.submit(class="btn-submit") }}
        </div>
    </form>
</body>
</html>

app/templates/homepage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Discover the latest products in fashion, electronics, and more on our classic e-commerce platform.">
    <meta name="keywords" content="ecommerce, fashion, electronics, shop, online, buy">
    <meta name="author" content="YourCompany">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <title>Classic Ecommerce</title>

    <link rel="stylesheet" href="../static/css/index.css">
</head>

<body>

    <header>
        <div class="logo">
            <img src="../static/images/logo.png" alt="Logo" width="100px" height="100px">
        </div>
        <div class="search-container">
            <input type="text" placeholder="Search products">
            <select id="catalog">
                <option value="all">All Departments</option>
                <option value="electronics">Electronics</option>
                <option value="fashion">Fashion</option>
                <option value="automotive">Automotive</option>
                <option value="books">Books</option>
                <option value="Boys Fashion">Boys Fashion</option>
                <option value="Computers">Computers</option>
                <option value="Men Fashion">Men Fashion</option>
                <option value="Movies">Movies and TV</option>
                <option value="Kitchen">Home & Kitchen</option>
                <option value="Arts">Arts & Crafts</option>
                <option value="music">Digital music</option>
            </select>
        </div>
    </header>

    <nav>
        <ul class="list">
            <li><a href="#">Home</a></li>
            <li><a href="#">Shop</a></li>
            <li><a href="#">About Us</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="{{ url_for('main.login') }}">Login</a></li>
            <li><a href="{{ url_for('main.register') }}">Sign Up</a></li>
        </ul>
    </nav>

     <section class="slideshow-container"></section>
        <div class="slideshow-images">
            <img src="../static/images/high-hills/image_0.jpg" alt="">
            <img src="../static/images/products/image6.jpg" alt="no images">
            <img src="../static/images/products/image2.jpg" alt="no images">
            <img src="../static/images/products/image4.jpg" alt="no images">
            <img src="../static/images/products/smartPhone-image_1.jpg" alt="">
        </div>
    </section>

    <section class="grid-container">
        <div class="grid-item">
            <img src="../static/images/bags/image_0.jpg" alt="Stylish Bag">
            <h3>Stylish Bag</h3>
            <p>Price: $45</p>
        </div>
        <div class="grid-item">
            <img src="../static/images/bags/image_2.jpg" alt="Elegant Handbag">
            <h3>Elegant Handbag</h3>
            <p>Price: $50</p>
        </div>
        <div class="grid-item">
            <img src="../static/images/men-trouser/image_0.jpg" alt="Men's Trousers">
            <h3>Men's Trousers</h3>
            <p>Price: $60</p>
        </div>
        <div class="grid-item">
            <img src="../static/images/crop-tops/image_0.jpg" alt="Women's Crop Top">
            <h3>Women's Crop Top</h3>
            <p>Price: $35</p>
        </div>
    </section>

    <section class="cta">
        <h2>Sign Up Today for Exclusive Offers!</h2>
        <button><a href="{{ url_for('main.register') }}">Get Started</a></button>
    </section>

    <footer class="footer">
        <div class="footer-col">
            <a href="#" class="footer-logo">
                <img src="../static/images/logo.png" alt="Logo" style="width: 100px; height: 100px;">
                <span>Tony Ecommerce</span>
            </a>
            <p>123 Street, City, Country</p>
        </div>
        <div class="footer-col">
            <h5>Quick Links</h5>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
                <li><a href="#">Services</a></li>
            </ul>
        </div>
        <div class="footer-col">
            <h5>Follow Us</h5>
            <ul>
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Instagram</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">LinkedIn</a></li>
            </ul>
        </div>
        <div class="footer-col map-col">
            <h5>Find Us</h5>
            <!-- Google Maps Embed -->
            <div class="map-container">
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3151.8354345094373!2d144.96305791532188!3d-37.816279742021886!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad65d43c1f0d091%3A0x5045675218ce6e0!2sMelbourne%20VIC%2C%20Australia!5e0!3m2!1sen!2sus!4v1631859729466!5m2!1sen!2sus"
                    allowfullscreen="" loading="lazy"></iframe>
            </div>
        </div>
    </footer>


</body>

</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello Tony</h1>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="../static/css/login.css">
</head>
<body>
    <header>
        <div class="header-container">
            <div class="query-info">
                <p><a href="#"><u>Tell us what you think</u></a></p>
            </div>
        </div>
    </header>

    <div class="main-container">
        <h1>Hello</h1>
        <p>Sign in to Tony_ecommerce or <a href="/register"><u>create an account</u></a></p>
        <form action="{{ url_for('main.login') }}" method="post">
            {{ form.hidden_tag() }}
            <div class="form-group" id="email">
                {{ form.email.label }}<br>
                {{ form.email(size=32) }}<br>
                {% for error in form.email.errors %}
                    <span class="error">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="form-group" id="password">
                {{ form.password.label }}<br>
                {{ form.password(size=32) }}<br>
                {% for error in form.password.errors %}
                    <span class="error">[{{ error }}]</span>
                {% endfor %}
            </div>
            
            
            <div class="form-group">
                {{ form.submit(class="btn-submit") }}
            </div>

            <div class="or-separator">
                <span>or</span>
            </div>

            <div class="facebook-login">
                <button class="btn-facebook"><h3>Continue with Facebook</h3></button>
            </div>

            <div class="google-login">
                <button class="btn-google"><h3>Continue with Google</h3></button>
            </div>
        </form>

        <div class="admin-login">
            <a href="{{ url_for('main.admin_login') }}"><button class="btn-google"><h3>Login as staff</h3></button></a>
        </div>
    </div>
</body>
</html>

app/templates/product_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Product</title>
    <link rel="stylesheet" href="../static/css/index.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/product_listing.css') }}">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/headers/"> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="Discover the latest products in fashion, electronics, and more on our classic e-commerce platform.">
    <meta name="keywords" content="ecommerce, fashion, electronics, shop, online, buy">
    <meta name="author" content="Anthony-Ecommerce">
    <!-- Canonical Link -->
    <link rel="canonical" href="https://donplackerr.tech/">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Bootstrap and Styles -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.2/font/bootstrap-icons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <header>
        <div class="header-container">
            <form>
                <div class="search-container">
                    <select id="catalog" name="catalog">
                        <option value="Electronics">All department</option>
                        <option value="Electronics">Electronics</option>
                        <option value="Boys Fashion">Boys Fashion</option>
                        <option value="Automotive">Automotive</option>
                        <option value="Men Fashion">Men Fashion</option>
                        <option value="Electronics">Baby</option>
                        <option value="Boys Fashion">Books</option>
                        <option value="Automotive">Computers</option>
                        <option value="Men Fashion">Men Fashion</option>
                        <option value="Electronics">Movies and TV</option>
                        <option value="Boys Fashion">Home & Kitchen</option>
                        <option value="Automotive">Arts & Crafts</option>
                        <option value="Men Fashion">Digital music</option>
                    </select>
                    <input type="text" name="search" id="search" placeholder="Search for products" autofocus>
                </div>
            </form>

            <div class="icon-container">
                <i class="fa-solid fa-bars" id="menu-icon"></i>
                <div class="dropdown-menu" id="dropdown-menu">
                    <a href="/profile">Profile</a>
                    <a href="/Setting">Setting</a>
                    <a href="/logout">Logout</a>
                </div>
                <a href="{{ url_for('main.view_cart') }}" class="cart-icon">
                    <i class="fa-solid fa-cat">
                        (<span id="cart-count">{{ session.get('cart', []) | length }}</span>)
                    </i>
                </a>

            </div>
        </div>
    </header>
    
    <main>
        <div class="container">
            <div class="row">
            {% for image in images %}
                <div class="col-md-3 mb-4">
                    <div class="card">
                        <!-- Ensure the _id is displayed correctly -->
                        <!-- {% if image._id %}
                            <p>{{ image._id }}</p>
                        {% else %}
                            <p>No image id</p>
                        {% endif %} -->
                        
                        <!-- Link to the product detail page with product_id -->
                        <div style="border: 10px 10px 10px 10px;">
                            <a href="{{ url_for('main.product_detail', product_id=image._id) }}">
                                <img src="{{ image.url }}" style="object-fit:cover; display: grid; width: 300px; height: 300px;" class="card-img-top" alt="{{ image.name }}">
                            </a>
                        </div>
                        
                        <div class="card-body">
                            {% if image.description %}
                                <p class="card-text" style="font-weight: bold; color: black;">
                                    {{ image.description }}
                                    <p>{{ image.name }} - ${{ image.price }}</p>
                                </p>
                            {% else %}
                                <p class="card-text">No description</p>
                            {% endif %}
                            
                            <!-- Add to Cart Button -->
                            <form action="{{ url_for('main.add_to_cart') }}" id="add-to-cart-form-{{ image._id }}" method="POST">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"> <!-- CSRF Token -->
                                <input type="hidden" name="product_id" value="{{ image._id }}"> 
                                <input type="number" name="quantity" value="1" min="1" required>
                                <button type="submit" class="add-to-cart-btn btn btn-warning mt-2" data-id="{{ image._id }}">
                                    Add to Cart <i class="fas fa-shopping-cart"></i>
                                </button>
                            </form>

                        </div>
                    </div>
                </div>
            {% endfor %}

            </div>

            <div class="pagination">
                {% if page > 1 %}
                <a href="{{ url_for('main.get_images', folder_name=folder_name, page=page-1) }}">&laquo; Previous</a>
                {% endif %}

                {% for p in range(1, total_pages + 1) %}
                    <a href="{{ url_for('main.get_images', folder_name=folder_name, page=p) }}" {% if p == page %}class="active"{% endif %}>{{ p }}</a>
                {% endfor %}

                {% if page < total_pages %}
                <a href="{{ url_for('main.get_images', folder_name=folder_name, page=page+1) }}">Next &raquo;</a>
                {% endif %}
            </div>
        </div>
    </main>

    <!-- Footer -->
    <footer class="bg-light py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <a href="/" class="footer-logo d-block mb-3">
                        <img src="../static/images/logo.png" alt="Footer Logo">
                    </a>
                </div>
                <div class="col-md-3">
                    <h5>Quick Links</h5>
                    <ul class="list-unstyled">
                        <li><a href="/">Home</a></li>
                        <li><a href="/shop">Shop</a></li>
                        <li><a href="/about">About Us</a></li>
                        <li><a href="/contact">Contact</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h5>Customer Service</h5>
                    <ul class="list-unstyled">
                        <li><a href="#">FAQs</a></li>
                        <li><a href="#">Shipping & Returns</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h5>Follow Us</h5>
                    <div class="footer-social-icons">
                        <a href="#" class="fab fa-facebook-f"></a>
                        <a href="#" class="fab fa-instagram"></a>
                        <a href="#" class="fab fa-twitter"></a>
                        <a href="#" class="fab fa-linkedin-in"></a>
                    </div>
                </div>
            </div>
            <div class="footer-bottom">
                <p>&copy; 2024 Tony_E-commerce. All rights reserved.</p>
            </div>
        </div>
    </footer>

    <!-- Scripts -->
     <script>
        $(document).ready(function() {
            $('.add-to-cart-btn').click(function(e) {
                e.preventDefault();

                const productId = $(this).data('id');
                const quantity = $(this).closest('form').find('input[name="quantity"]').val();
                const csrfToken = $(this).closest('form').find('input[name="csrf_token"]').val(); // Get CSRF token

                $.ajax({
                    url: "{{ url_for('main.add_to_cart') }}",
                    type: "POST",
                    contentType: "application/json",
                    dataType: "json",
                    data: JSON.stringify({
                        product_id: productId,
                        quantity: quantity,
                        csrf_token: csrfToken
                    }),
                    success: function(response) {
                        alert('Product added to cart');
                        $('#cart-count').text(response.cart_count);
                    },
                    error: function(xhr, status, error) {
                        alert('Failed to add the product to the cart: ' + xhr.responseText);
                    }
                });
            });
        });


    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>